
package com.mattel.ecomm.esb.launchpad.addressvalidation.service.validateaddressservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.mattel.ecomm.esb.cdm.dtc.validateaddress.components1.ValidateAddressRequestType;
import com.mattel.ecomm.esb.cdm.dtc.validateaddress.components1.ValidateAddressResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ValidateAddressServiceInterface", targetNamespace = "http://www.mattel.com/esb/launchpad/addressvalidation/service/validateaddressservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.mattel.ecomm.esb.cdm.dtc.common.core1.ObjectFactory.class,
    com.mattel.ecomm.esb.cdm.dtc.validateaddress.components1.ObjectFactory.class,
    com.mattel.ecomm.esb.cdm.dtc.validateaddress.core1.ObjectFactory.class
})
public interface ValidateAddressServiceInterface {


    /**
     * 
     * @param validateAddressInput
     * @return
     *     returns com.mattel.esb.cdm.dtc.validateaddress.components1.ValidateAddressResponseType
     */
    @WebMethod(action = "/ValidateAddressHTTPListener/StarterProcesses/ServiceAgents/ValidateAddressSOAPHTTPStarter.serviceagent/validateAddressServiceEndpoint/validateAddress")
    @WebResult(name = "validateAddressResponse", targetNamespace = "http://www.mattel.com/esb/cdm/dtc/validateaddress/components1", partName = "validateAddressOutput")
    ValidateAddressResponseType validateAddress(
        @WebParam(name = "validateAddressRequest", targetNamespace = "http://www.mattel.com/esb/cdm/dtc/validateaddress/components1", partName = "validateAddressInput")
        ValidateAddressRequestType validateAddressInput);

}
