
package com.mattel.ecomm.esb.launchpad.addressvalidation.service.validateaddressservice;

//import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidateAddressSOAPHTTPStarter.serviceagent", targetNamespace = "http://www.mattel.com/esb/launchpad/addressvalidation/service/validateaddressservice", wsdlLocation = "file:/D:/Development_Avecto/CODE1/AEM-Main/mattel-web/ValidateAddressSOAPHTTPStarter.wsdl")
public class ValidateAddressSOAPHTTPStarterServiceagent
    extends Service
{

    private final static URL VALIDATEADDRESSSOAPHTTPSTARTERSERVICEAGENT_WSDL_LOCATION;
    private final static WebServiceException VALIDATEADDRESSSOAPHTTPSTARTERSERVICEAGENT_EXCEPTION;
    private final static QName VALIDATEADDRESSSOAPHTTPSTARTERSERVICEAGENT_QNAME = new QName("http://www.mattel.com/esb/launchpad/addressvalidation/service/validateaddressservice", "ValidateAddressSOAPHTTPStarter.serviceagent");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
           url = ValidateAddressSOAPHTTPStarterServiceagent.class.getResource("ValidateAddressSOAPHTTPStarter.wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        VALIDATEADDRESSSOAPHTTPSTARTERSERVICEAGENT_WSDL_LOCATION = url;
        VALIDATEADDRESSSOAPHTTPSTARTERSERVICEAGENT_EXCEPTION = e;
    }

    public ValidateAddressSOAPHTTPStarterServiceagent() {
        super(__getWsdlLocation(), VALIDATEADDRESSSOAPHTTPSTARTERSERVICEAGENT_QNAME);
    }

    public ValidateAddressSOAPHTTPStarterServiceagent(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDATEADDRESSSOAPHTTPSTARTERSERVICEAGENT_QNAME, features);
    }

    public ValidateAddressSOAPHTTPStarterServiceagent(URL wsdlLocation) {
        super(wsdlLocation, VALIDATEADDRESSSOAPHTTPSTARTERSERVICEAGENT_QNAME);
    }

    public ValidateAddressSOAPHTTPStarterServiceagent(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDATEADDRESSSOAPHTTPSTARTERSERVICEAGENT_QNAME, features);
    }

    public ValidateAddressSOAPHTTPStarterServiceagent(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidateAddressSOAPHTTPStarterServiceagent(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidateAddressServiceInterface
     */
    @WebEndpoint(name = "ValidateAddressServiceInterfaceEndpoint")
    public ValidateAddressServiceInterface getValidateAddressServiceInterfaceEndpoint() {
        return super.getPort(new QName("http://www.mattel.com/esb/launchpad/addressvalidation/service/validateaddressservice", "ValidateAddressServiceInterfaceEndpoint"), ValidateAddressServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidateAddressServiceInterface
     */
    @WebEndpoint(name = "ValidateAddressServiceInterfaceEndpoint")
    public ValidateAddressServiceInterface getValidateAddressServiceInterfaceEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.mattel.com/esb/launchpad/addressvalidation/service/validateaddressservice", "ValidateAddressServiceInterfaceEndpoint"), ValidateAddressServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDATEADDRESSSOAPHTTPSTARTERSERVICEAGENT_EXCEPTION!= null) {
            throw VALIDATEADDRESSSOAPHTTPSTARTERSERVICEAGENT_EXCEPTION;
        }
        return VALIDATEADDRESSSOAPHTTPSTARTERSERVICEAGENT_WSDL_LOCATION;
    }

}
